# Generated by Django 2.2.16 on 2020-10-22 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matematicaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tipo', models.CharField(choices=[('P', 'Professor'), ('E', 'Estudante')], default='E', max_length=20, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='estudante',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='estudante',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='ano_de_escolaridade',
            field=models.CharField(choices=[('1', '1º ano do EF'), ('2', '2º ano do EF'), ('3', '3º ano do EF'), ('4', '4º ano do EF'), ('5', '5º ano do EF'), ('6', '6º ano do EF'), ('7', '7º ano do EF'), ('8', '8º ano do EF'), ('9', '9º ano do EF'), ('10', '1º ano do EM'), ('11', '2º ano do EM'), ('12', '3º ano do EM')], default='1', max_length=20),
        ),
    ]
