# Generated by Django 2.2.16 on 2020-10-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matematicaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='ano_de_escolaridade',
        ),
    ]
