# Generated by Django 2.2.16 on 2020-10-15 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matematicaapp', '0002_remove_estudante_ano_de_escolaridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
