# Generated by Django 2.2.16 on 2020-10-20 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matematicaapp', '0003_estudante_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
