# Generated by Django 2.2.16 on 2020-10-23 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matematicaapp', '0003_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificuldade', models.CharField(choices=[('1', 'facil'), ('2', 'medio'), ('3', 'dificil')], default='3', max_length=20)),
                ('area', models.CharField(choices=[('1', 'artmetica'), ('2', 'geometria'), ('3', 'algebra')], default='3', max_length=20)),
                ('anos_de_escolaridade', models.CharField(choices=[('1', '1º ano do EF'), ('2', '2º ano do EF'), ('3', '3º ano do EF'), ('4', '4º ano do EF'), ('5', '5º ano do EF'), ('6', '6º ano do EF'), ('7', '7º ano do EF'), ('8', '8º ano do EF'), ('9', '9º ano do EF'), ('10', '1º ano do EM'), ('11', '2º ano do EM'), ('12', '3º ano do EM')], default='12', max_length=20)),
                ('fonte', models.TextField()),
                ('enunciado', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
