# Generated by Django 2.2.16 on 2020-11-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematicaapp', '0005_auto_20201030_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='figura',
            field=models.FileField(default='12', upload_to='../static/assets/questoes5ano'),
        ),
    ]
