# Generated by Django 2.2.16 on 2020-11-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematicaapp', '0007_auto_20201102_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='figura',
            field=models.FileField(blank=True, upload_to='static/assets/questoes5ano'),
        ),
    ]
