# Generated by Django 2.2.16 on 2020-11-02 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matematicaapp', '0010_auto_20201102_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='resposta',
            field=models.IntegerField(default='1'),
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=20000)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matematicaapp.Questao')),
            ],
        ),
    ]
